# This file was generated by GoReleaser. DO NOT EDIT.
cask "sift" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "2f9abccd54ac31ebae95257c83483d365e0ddddcf14fd64b8b827bf0146fba97"
      url "https://github.com/Anshika2203/sift/releases/download/v#{version}/sift_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5cce5a3b6e0bd9429846905a78873a4190907b51b887dce2394f52b55d7be85f"
      url "https://github.com/Anshika2203/sift/releases/download/v#{version}/sift_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3f3f3008b45fdbedc0ea3bf249894064927b7ef8e21d8eef8964072409f1232c"
      url "https://github.com/Anshika2203/sift/releases/download/v#{version}/sift_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "382838ae508c452760034ec0c81d2b3f4f1b110713d145d59cc98a96715a0b76"
      url "https://github.com/Anshika2203/sift/releases/download/v#{version}/sift_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sift"
  desc "A fast, interactive command-line fuzzy finder."
  homepage "https://github.com/Anshika2203/sift"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sift"

  # No zap stanza required

end
