# This file was generated by GoReleaser. DO NOT EDIT.
cask "sift" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "10982e07228aee959623fe4c72a9b7653694cad1855049049b2f29f63e5ededf"
      url "https://github.com/Anshika2203/sift/releases/download/v#{version}/sift_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e23b855aa64d70634d3d01aeb6e2827c67eb1eba027cbd45420e22187324a41"
      url "https://github.com/Anshika2203/sift/releases/download/v#{version}/sift_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b91207f7ead84adf812f5cb612a6700906340262d6bf60bd9143919031ec19bb"
      url "https://github.com/Anshika2203/sift/releases/download/v#{version}/sift_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "81ee71a28d8619410c1e11bdacd9e4d4a3492586d0fe09578dcc43595aa6b753"
      url "https://github.com/Anshika2203/sift/releases/download/v#{version}/sift_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sift"
  desc "A fast, interactive command-line fuzzy finder."
  homepage "https://github.com/Anshika2203/sift"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sift"

  # No zap stanza required

end
