# This file was generated by GoReleaser. DO NOT EDIT.
cask "sift" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "f1a8d9049f275cbdd093678946ceb80cc3b43e73d0f7e545da80a86edf2af526"
      url "https://github.com/Anshika2203/sift/releases/download/v#{version}/sift_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "474930154a293efd0e69a3e9c1fb9323e3d55f8309c11cf50fb5d56676905253"
      url "https://github.com/Anshika2203/sift/releases/download/v#{version}/sift_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "50edb1e800a37f6c76c2145c2bcf7de229d667554bd62feb6782a4aa4ee75150"
      url "https://github.com/Anshika2203/sift/releases/download/v#{version}/sift_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "82c2a106e53918dadedf7e455be819067658b1f78a2d4f7ccc67b194e9859f7b"
      url "https://github.com/Anshika2203/sift/releases/download/v#{version}/sift_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sift"
  desc "A fast, interactive command-line fuzzy finder."
  homepage "https://github.com/Anshika2203/sift"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sift"

  # No zap stanza required

end
